### ISSUE TITLE
Crash to Desktop and Corrupted Save

### ISSUE THREAD

**Issue by madflavius** [Gaelmare/dynamictreestfc#15]
Was running at a higher tick speed to generate JoCodes (randomTickSpeed 100).

Crashed when I clicked a tree to cut it down in creative mode; the falling occurs normally, but when the tree hits the ground and stops, crash to desktop.

 Got this crash report:

Description: Ticking entity

java.lang.IllegalStateException: ChunkData capability is missing.
	at org.labellum.mc.dynamictreestfc.blocks.BlockRootyTFC.getDecayBlockState(BlockRootyTFC.java:28)
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.updateTree(BlockRooty.java:182)
	at com.ferreusveritas.dynamictrees.blocks.BlockRooty.func_180645_a(BlockRooty.java:148)
	at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.cleanupRootyDirt(EntityFallingTree.java:413)
	at com.ferreusveritas.dynamictrees.entities.animation.AnimationHandlerFallover.shouldDie(AnimationHandlerFallover.java:244)
	at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.shouldDie(EntityFallingTree.java:353)
	at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.func_70030_z(EntityFallingTree.java:270)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
---

Haven't been able to reopen the world save. I've now repro'd this one more time.

**Comment by madflavius** [comment]
Upon further introspection, I _think_ it's because there's no chunkdata to query in a SuperFlat world.
