### ISSUE TITLE
unreleased code has NPE

### ISSUE THREAD

**Issue by Gaelmare** [Gaelmare/dynamictreestfc#39]
I started to break the rootydirt block below a DTTFC tree, and got this crash/stacktrace. Ideas, @eerussianguy?

```
[14:44:42] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: null
        at com.ferreusveritas.dynamictrees.models.bakedmodels.BakedModelBlockRooty.getParticleTexture(BakedModelBlockRooty.java:73) ~[BakedModelBlockRooty.class:?]
        at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SimpleBakedModel.java:92) ~[SimpleBakedModel$Builder.class:?]
        at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:835) ~[ForgeHooksClient.class:?]
        at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlockDamage(BlockRendererDispatcher.java:46) ~[BlockRendererDispatcher.class:?]
        at net.minecraft.client.renderer.RenderGlobal.drawBlockDamageTexture(RenderGlobal.java:1938) ~[RenderGlobal.class:?]
        at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1375) ~[EntityRenderer.class:?]
        at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259) ~[EntityRenderer.class:?]
        at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062) ~[EntityRenderer.class:?]
        at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[Minecraft.class:?]
        at net.minecraft.client.Minecraft.run(Minecraft.java:398) [Minecraft.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
        at GradleStart.main(GradleStart.java:25) [start/:?]
[14:44:42] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:553]: ---- Minecraft Crash Report ----
// I let you down. Sorry :(
```

**Comment by eerussianguy** [comment]
getParticleTexture() or something to that effect needs to be overridden in the class to get the mimic value
