### ISSUE TITLE
Breaking tree or branches crashes from not having a placed property ala blocklogtfc

### ISSUE THREAD

**Issue by Gaelmare** [Gaelmare/dynamictreestfc#5]
I see two options to fix
1) make a new blocklogdttfc which doesn't have a differing hardness
2) get the placed property saved with the extended property

**Comment by Gaelmare** [comment]
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=placed, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=dynamictreestfc:block/branch/douglas_fir, properties=[radius]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:204)
	at net.dries007.tfc.objects.blocks.wood.BlockLogTFC.getBlockHardness(BlockLogTFC.java:104)
	at com.ferreusveritas.dynamictrees.blocks.BlockBranchBasic.getBlockHardness(BlockBranchBasic.java:180)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getBlockHardness(BlockStateContainer.java:415)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:252)
	at net.minecraft.block.Block.getPlayerRelativeBlockHardness(Block.java:774)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getPlayerRelativeBlockHardness(BlockStateContainer.java:420)
	at net.minecraft.client.multiplayer.PlayerControllerMP.clickBlock(PlayerControllerMP.java:269)
	at net.minecraft.client.Minecraft.clickMouse(Minecraft.java:1630)
	at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2376)
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2147)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1935)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1188)
	at net.minecraft.client.Minecraft.run(Minecraft.java:442)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:204)
	at net.dries007.tfc.objects.blocks.wood.BlockLogTFC.getBlockHardness(BlockLogTFC.java:104)
	at com.ferreusveritas.dynamictrees.blocks.BlockBranchBasic.getBlockHardness(BlockBranchBasic.java:180)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getBlockHardness(BlockStateContainer.java:415)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:252)
	at net.minecraft.block.Block.getPlayerRelativeBlockHardness(Block.java:774)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getPlayerRelativeBlockHardness(BlockStateContainer.java:420)
	at net.minecraft.client.multiplayer.PlayerControllerMP.clickBlock(PlayerControllerMP.java:269)
	at net.minecraft.client.Minecraft.clickMouse(Minecraft.java:1630)
	at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2376)
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2147)

**Comment by Gaelmare** [comment]
Fixed via not setting the DT primitiveLog to a BlockLogTFC. Unfortunately, this creates a new issue.
