### ISSUE TITLE
Fatal error with PalmLeavesBakedModel

### ISSUE THREAD

**Issue by renanbomtempo** [Gaelmare/dynamictreestfc#52]
```
Description: Tesselating block model

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.BakedModel.getQuads(net.minecraft.world.level.block.state.BlockState, net.minecraft.core.Direction, net.minecraft.util.RandomSource, net.minecraftforge.client.model.data.ModelData, net.minecraft.client.renderer.RenderType)" because "this.bakedFronds[...]" is null
	at org.labellum.mc.dttfc.client.PalmLeavesBakedModel.getQuads(PalmLeavesBakedModel.java:215) ~[DynamicTreesTFC-1.20.1-2.0.0-alpha1.jar%23349!/:2.0.0-alpha1] {re:classloading}
	at net.minecraft.client.resources.model.MultiPartBakedModel.getQuads(MultiPartBakedModel.java:77) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.dedupmultipart.mixin.json:MixinMultipartModel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithoutAO(ModelBlockRenderer.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.lighting.ForgeModelBlockRenderer.tesselateWithoutAO(ForgeModelBlockRenderer.java:52) ~[forge-1.20.1-47.3.7-universal.jar%23441!/:?] {re:mixin,re:classloading,pl:mixin:APP:creativecore.forge.mixins.json:ForgeModelBlockRendererAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:68) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:farmersdelight.mixins.json:HideBlockBreakProgressMixin,pl:mixin:APP:physicsmod.mixins.json:vines.MixinBlockRenderManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:641) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.RebuildTaskMixin,pl:mixin:APP:flywheel.mixins.json:instancemanage.ChunkRebuildHooksMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.chunk_meshing.RebuildTaskMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:556) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.RebuildTaskMixin,pl:mixin:APP:flywheel.mixins.json:instancemanage.ChunkRebuildHooksMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.chunk_meshing.RebuildTaskMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.m_194412_(ChunkRenderDispatcher.java:128) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Dynamic Trees TFC (dttfc), Version: 2.0.0-alpha1
		Issue tracker URL: https://github.com/Gaelmare/dynamictreestfc/issues
		at TRANSFORMER/dttfc@2.0.0-alpha1/org.labellum.mc.dttfc.client.PalmLeavesBakedModel.getQuads(PalmLeavesBakedModel.java:215)
Stacktrace:
	at org.labellum.mc.dttfc.client.PalmLeavesBakedModel.getQuads(PalmLeavesBakedModel.java:215) ~[DynamicTreesTFC-1.20.1-2.0.0-alpha1.jar%23349!/:2.0.0-alpha1] {re:classloading}
	at net.minecraft.client.resources.model.MultiPartBakedModel.getQuads(MultiPartBakedModel.java:77) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.dedupmultipart.mixin.json:MixinMultipartModel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithoutAO(ModelBlockRenderer.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.lighting.ForgeModelBlockRenderer.tesselateWithoutAO(ForgeModelBlockRenderer.java:52) ~[forge-1.20.1-47.3.7-universal.jar%23441!/:?] {re:mixin,re:classloading,pl:mixin:APP:creativecore.forge.mixins.json:ForgeModelBlockRendererAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Block model being tesselated --
Details:
	Block: Block{dttfc:palm_leaves}[direction=6,distance=1,persistent=false,waterlogged=false]
	Block location: World: (9439,71,9967), Section: (at 15,7,15 in 589,4,622; chunk contains blocks 9424,-64,9952 to 9439,319,9967), Region: (18,19; contains chunks 576,608 to 607,639, blocks 9216,-64,9728 to 9727,319,10239)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:68) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:farmersdelight.mixins.json:HideBlockBreakProgressMixin,pl:mixin:APP:physicsmod.mixins.json:vines.MixinBlockRenderManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:641) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.RebuildTaskMixin,pl:mixin:APP:flywheel.mixins.json:instancemanage.ChunkRebuildHooksMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.chunk_meshing.RebuildTaskMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:556) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.RebuildTaskMixin,pl:mixin:APP:flywheel.mixins.json:instancemanage.ChunkRebuildHooksMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.chunk_meshing.RebuildTaskMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.m_194412_(ChunkRenderDispatcher.java:128) ~[client-1.20.1-20230612.114412-srg.jar%23436!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
```

**Comment by Gaelmare** [comment]
Please share an https://mclo.gs version of your log file where this crash
happened.

Any information about when and how this occured would also be great. Which
Modpack?

**Comment by renanbomtempo** [comment]
> Please share an https://mclo.gs/ version of your log file where this crash happened.

Sure, here is the [complete crash report](https://mclo.gs/Vt490G5).


> Any information about when and how this occured would also be great. 

I'd just stumbled upon a biome where there were some palm trees and the game just crashed. Every time I open the save file it loads in the same spot, and the game crashes within a couple of seconds.


> Which Modpack?

I'm using the [Divine Technology Modpack - Terra](https://www.curseforge.com/minecraft/modpacks/divine-technology-pack-terra) as a basis, but I've added and removed quite a few mods. The full list is included in the crash report.

**Comment by drhaber** [comment]
I suspect I am having the same issue 
https://mclo.gs/nrfBWtj

**Comment by ahhhh6980** [comment]
I am having a similar issue 
https://mclo.gs/hxJ76JJ

**Comment by Gaelmare** [comment]
Should be fixed with current release.
