### ISSUE TITLE
at savanna in  Minecraft Forge 1.20.1 crash

### ISSUE THREAD

**Issue by Wangrenze9788** [Gaelmare/dynamictreestfc#55]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-12-07 13:42:35
Description: Exception generating new chunk

java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=direction, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8]} as it does not exist in Block{minecraft:air}
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:122) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.PalmLeavesProperties$DynamicPalmLeavesBlock.getDirectionState(PalmLeavesProperties.java:148) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.PalmLeavesProperties$DynamicPalmLeavesBlock.getLeavesBlockStateForPlacement(PalmLeavesProperties.java:171) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.DynamicLeavesBlock.updateHydro(DynamicLeavesBlock.java:245) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.DynamicLeavesBlock.updateLeaves(DynamicLeavesBlock.java:196) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.DynamicLeavesBlock.age(DynamicLeavesBlock.java:145) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.api.TreeHelper.ageVolume(TreeHelper.java:74) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.worldgen.JoCode.generateAndAgeLeaves(JoCode.java:260) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.worldgen.JoCode.generate(JoCode.java:214) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.tree.species.Species.generate(Species.java:2135) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at org.labellum.mc.dttfc.util.DynamicForestFeature.generateTree(DynamicForestFeature.java:140) ~[DynamicTreesTFC-1.20.1-2.0.1.jar%23163!/:2.0.1] {re:classloading}
	at org.labellum.mc.dttfc.util.DynamicForestFeature.generateTrees(DynamicForestFeature.java:103) ~[DynamicTreesTFC-1.20.1-2.0.1.jar%23163!/:2.0.1] {re:classloading}
	at org.labellum.mc.dttfc.util.DynamicForestFeature.lambda$place$0(DynamicForestFeature.java:81) ~[DynamicTreesTFC-1.20.1-2.0.1.jar%23163!/:2.0.1] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {re:computing_frames}
	at org.labellum.mc.dttfc.util.DynamicForestFeature.m_142674_(DynamicForestFeature.java:78) ~[DynamicTreesTFC-1.20.1-2.0.1.jar%23163!/:2.0.1] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:53) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:42) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.dries007.tfc.world.TFCChunkGenerator.m_213609_(TFCChunkGenerator.java:369) ~[TerraFirmaCraft-Forge-1.20.1-3.2.11.jar%23165!/:3.2.11] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading,pl:mixin:APP:tfc.mixins.json:ChunkMapMixin,pl:mixin:APP:tfc.mixins.json:accessor.ChunkMapAccessor,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2393!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading,pl:mixin:APP:tfc.mixins.json:ChunkMapMixin,pl:mixin:APP:tfc.mixins.json:accessor.ChunkMapAccessor,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mods: 
	Dynamic Trees TFC (dttfc), Version: 2.0.1
		Issue tracker URL: https://github.com/Gaelmare/dynamictreestfc/issues
		at TRANSFORMER/dttfc@2.0.1/org.labellum.mc.dttfc.util.DynamicForestFeature.generateTree(DynamicForestFeature.java:140)

	TerraFirmaCraft (tfc), Version: 3.2.11
		Issue tracker URL: https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues
		at TRANSFORMER/tfc@3.2.11/net.dries007.tfc.world.TFCChunkGenerator.m_213609_(TFCChunkGenerator.java:369)

	Dynamic Trees (dynamictrees), Version: 1.20.1-1.4.0-ALPHA03
		Issue tracker URL: https://github.com/DynamicTreesTeam/DynamicTrees/issues
		at TRANSFORMER/dynamictrees@1.20.1-1.4.0-ALPHA03/com.ferreusveritas.dynamictrees.block.leaves.PalmLeavesProperties$DynamicPalmLeavesBlock.getDirectionState(PalmLeavesProperties.java:148)
Stacktrace:
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:122) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.PalmLeavesProperties$DynamicPalmLeavesBlock.getDirectionState(PalmLeavesProperties.java:148) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.PalmLeavesProperties$DynamicPalmLeavesBlock.getLeavesBlockStateForPlacement(PalmLeavesProperties.java:171) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.DynamicLeavesBlock.updateHydro(DynamicLeavesBlock.java:245) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.DynamicLeavesBlock.updateLeaves(DynamicLeavesBlock.java:196) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.block.leaves.DynamicLeavesBlock.age(DynamicLeavesBlock.java:145) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.api.TreeHelper.ageVolume(TreeHelper.java:74) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.worldgen.JoCode.generateAndAgeLeaves(JoCode.java:260) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.worldgen.JoCode.generate(JoCode.java:214) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at com.ferreusveritas.dynamictrees.tree.species.Species.generate(Species.java:2135) ~[DynamicTrees-1.20.1-1.4.0-ALPHA03.jar%23161!/:1.20.1-1.4.0-ALPHA03] {re:classloading}
	at org.labellum.mc.dttfc.util.DynamicForestFeature.generateTree(DynamicForestFeature.java:140) ~[DynamicTreesTFC-1.20.1-2.0.1.jar%23163!/:2.0.1] {re:classloading}
	at org.labellum.mc.dttfc.util.DynamicForestFeature.generateTrees(DynamicForestFeature.java:103) ~[DynamicTreesTFC-1.20.1-2.0.1.jar%23163!/:2.0.1] {re:classloading}
	at org.labellum.mc.dttfc.util.DynamicForestFeature.lambda$place$0(DynamicForestFeature.java:81) ~[DynamicTreesTFC-1.20.1-2.0.1.jar%23163!/:2.0.1] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {re:computing_frames}
	at org.labellum.mc.dttfc.util.DynamicForestFeature.m_142674_(DynamicForestFeature.java:78) ~[DynamicTreesTFC-1.20.1-2.0.1.jar%23163!/:2.0.1] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:53) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:42) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.dries007.tfc.world.TFCChunkGenerator.m_213609_(TFCChunkGenerator.java:369) ~[TerraFirmaCraft-Forge-1.20.1-3.2.11.jar%23165!/:3.2.11] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading,pl:mixin:APP:tfc.mixins.json:ChunkMapMixin,pl:mixin:APP:tfc.mixins.json:accessor.ChunkMapAccessor,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2393!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading,pl:mixin:APP:tfc.mixins.json:ChunkMapMixin,pl:mixin:APP:tfc.mixins.json:accessor.ChunkMapAccessor,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
-- Chunk to be generated --
Details:
	Location: -235,476
	Position hash: 2048699399957
	Generator: net.dries007.tfc.world.TFCChunkGenerator@4b30147d
Stacktrace:
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading,pl:mixin:APP:tfc.mixins.json:ChunkMapMixin,pl:mixin:APP:tfc.mixins.json:accessor.ChunkMapAccessor,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2393!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading,pl:mixin:APP:tfc.mixins.json:ChunkMapMixin,pl:mixin:APP:tfc.mixins.json:accessor.ChunkMapAccessor,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Wangrenze9788'/35, l='ServerLevel[新的世界]', x=-3494.40, y=75.22, z=7589.20]]
	Chunk stats: 5228
	Level dimension: minecraft:overworld
	Level spawn location: World: (1456,88,-2512), Section: (at 0,8,0 in 91,5,-157; chunk contains blocks 1456,-64,-2512 to 1471,319,-2497), Region: (2,-5; contains chunks 64,-160 to 95,-129, blocks 1024,-64,-2560 to 1535,319,-2049)
	Level time: 1978269 game time, 2625186 day time
	Level name: 新的世界
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 2268 (now: false), thunder time: 49070 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), BellSoft
	Memory: 2580409120 bytes (2460 MiB) / 5494538240 bytes (5240 MiB) up to 10200547328 bytes (9728 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: OrayIddDriver Device
	Graphics card #0 vendor: Shanghai Best Oray Information Technology Co., Ltd.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=17.1.58.818
	Graphics card #1 name: IddSampleDriver Device HDR
	Graphics card #1 vendor: <Your manufacturer name>
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=23.34.25.279
	Graphics card #2 name: Intel(R) UHD Graphics
	Graphics card #2 vendor: Intel Corporation (0x8086)
	Graphics card #2 VRAM (MB): 1024.00
	Graphics card #2 deviceId: 0x9a60
	Graphics card #2 versionInfo: DriverVersion=30.0.101.2079
	Graphics card #3 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #3 vendor: NVIDIA (0x10de)
	Graphics card #3 VRAM (MB): 4095.00
	Graphics card #3 deviceId: 0x2520
	Graphics card #3 versionInfo: DriverVersion=32.0.15.6614
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37411.30
	Virtual memory used (MB): 22149.05
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 113.31
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1459m -Xmx9728m
	Server Running: true
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Player Count: 1 / 8; [ServerPlayer['Wangrenze9788'/35, l='ServerLevel[新的世界]', x=-3494.40, y=75.22, z=7589.20]]
	Data Packs: vanilla, mod:patchouli (incompatible), mod:dynamictrees (incompatible), mod:dynamictreesplus (incompatible), mod:forge, mod:tfc, mod:dttfc (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: TerraFirmaCraft Remake
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.3.11-universal.jar                |Forge                         |forge                         |47.3.11             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		TerraFirmaCraft-Forge-1.20.1-3.2.11.jar           |TerraFirmaCraft               |tfc                           |3.2.11              |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.20.1-1.4.0-ALPHA03.jar             |Dynamic Trees                 |dynamictrees                  |1.20.1-1.4.0-ALPHA03|DONE      |Manifest: NOSIGNATURE
		DynamicTreesPlus-1.20.1-1.2.0-BETA3.jar           |Dynamic Trees Plus            |dynamictreesplus              |1.20.1-1.2.0-BETA3  |DONE      |Manifest: NOSIGNATURE
		DynamicTreesTFC-1.20.1-2.0.1.jar                  |Dynamic Trees TFC             |dttfc                         |2.0.1               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 0a66847d-01d0-4ee5-95e1-0e604fa6613b
	FML: 47.3
	Forge: net.minecraftforge:47.3.11

**Comment by Wangrenze9788** [comment]
crash report on mclogs: https://mclo.gs/CJ5FRQ6

**Comment by Wangrenze9788** [comment]
duplicate with 52#

**Comment by Wangrenze9788** [comment]
issue in Dynamic Trees 1.4.0 version
